In [1]:
print("hellow")

hellow


In [4]:
a=5
print(a)
a

5


5

In [9]:
type(a)

int

In [10]:
b="bobby"
type(b)

str

In [11]:
c=True
type(c)

bool

In [12]:
d=9.7
type(d)

float

In [13]:
#float to int
age=23.5
age=int(age)
age

23

In [ ]:
#type castinf str to int
num= int('2')+5
num

7

In [15]:
e=15
f=8
g=7.8
s='hello'

In [16]:
e+f

23

In [19]:
f-g


0.20000000000000018

In [20]:
g/f

0.975

In [21]:
e**g

1491117340.1565564

In [22]:
f//g

1.0

In [23]:
e==f

False

In [24]:
f>g

True

In [25]:
type(a==b)

bool

In [27]:
c<e

True

In [28]:
(1==1) and (2==2)

True

In [31]:
(1==1) and (0==9)

False

In [36]:
#conditional statement
x=80
if(x==90):
    print("ans is right!")
elif(x<100):
    print("lezgooo")
else:
    print("nahhh")

lezgooo


In [39]:
y=input()
y=int(y)
if(y%2==0):
    print("trueee")
else:
    print("falseee")

falseee


In [41]:
#loopingg
for x in range(4):
    print(x)

0
1
2
3


In [42]:
for i in range(1,5):
    print(i)

1
2
3
4


In [43]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [44]:
for i in range(1, 10, 2):
    print(i, end=' ')

1 3 5 7 9 

In [45]:
for char in "bobby":
    print(char)

b
o
b
b
y


In [46]:
for x in range(1, 3):
    for y in "abc":
        print(x,y)

1 a
1 b
1 c
2 a
2 b
2 c


In [49]:
i=1
while(i<5):
    print(i)
    i+=1

1
2
3
4


In [1]:
def welcome():
    print("heyyyy")

welcome()

heyyyy


In [4]:
def add(a, b):
    ans=a+b
    return ans
add(1,2)


3

In [5]:
name="bob"
def func():
    global name
    name="riya"
    return name
func()

'riya'

In [2]:
import numpy as np

In [3]:
matrix = np.arange(1,13)
matrix= matrix.reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
raveld = matrix.ravel()
raveld

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
trans = matrix.transpose()
trans

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])