In [1]:
import numpy as np

In [3]:
rng = np.random.default_rng(seed=42)
print(rng)

Generator(PCG64)


In [5]:
list_data = [1,2,3,4]
arr = np.array(list_data)
print(arr)

[1 2 3 4]


In [7]:
zeros = np.zeros((2,3))
print(zeros)
ones = np.ones((4,5))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
array = np.arange(2,15,2)
print(array)

[ 2  4  6  8 10 12 14]


In [11]:
ans = np.linspace(0,1,5)
print(ans)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
ar = np.array([10,20,30,40,50])
print(ar[3])

40


In [13]:
print(ar[1:4])

[20 30 40]


In [14]:
print(ar[::2])

[10 30 50]


In [20]:
a= np.array([[1,2,3],
              [4,5,6],
              [8,9,10]])
print(a[1,2])
print(a[0:2, 1:3])
print(a[0:2, :])

6
[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
bool_mask = (a>4) & (a<10)
print(bool_mask)

[[False False False]
 [False  True  True]
 [ True  True False]]


In [ ]:
#shape
